//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenETaxBill.WcfResponsor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07", ConfigurationName="WcfResponsor.IResponseService")]
    public interface IResponseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/Wr" +
            "iteLog", ReplyAction="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/Wr" +
            "iteLogResponse")]
        void WriteLog(System.Guid p_certapp, string p_exception, string p_message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/Wr" +
            "iteLog", ReplyAction="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/Wr" +
            "iteLogResponse")]
        System.Threading.Tasks.Task WriteLogAsync(System.Guid p_certapp, string p_exception, string p_message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/He" +
            "lloWorld", ReplyAction="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/He" +
            "lloWorldResponse")]
        string HelloWorld(System.Guid p_certapp, string p_greeting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/He" +
            "lloWorld", ReplyAction="http://www.odinsoftware.co.kr/open/etaxbill/responsor/2016/07/IResponseService/He" +
            "lloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(System.Guid p_certapp, string p_greeting);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResponseServiceChannel : OpenETaxBill.WcfResponsor.IResponseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResponseServiceClient : System.ServiceModel.ClientBase<OpenETaxBill.WcfResponsor.IResponseService>, OpenETaxBill.WcfResponsor.IResponseService {
        
        public ResponseServiceClient() {
        }
        
        public ResponseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResponseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResponseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResponseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WriteLog(System.Guid p_certapp, string p_exception, string p_message) {
            base.Channel.WriteLog(p_certapp, p_exception, p_message);
        }
        
        public System.Threading.Tasks.Task WriteLogAsync(System.Guid p_certapp, string p_exception, string p_message) {
            return base.Channel.WriteLogAsync(p_certapp, p_exception, p_message);
        }
        
        public string HelloWorld(System.Guid p_certapp, string p_greeting) {
            return base.Channel.HelloWorld(p_certapp, p_greeting);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(System.Guid p_certapp, string p_greeting) {
            return base.Channel.HelloWorldAsync(p_certapp, p_greeting);
        }
    }
}
